// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operational counters exposed to authenticated administrators.
 */
export type AdminMetricsResponse = { 
/**
 * Total number of recognized project directories under the configured root.
 */
projects: number, 
/**
 * Number of in-memory project sessions currently retained.
 */
active_sessions: number, 
/**
 * Number of sessions with a tracked compiler process.
 */
active_builds: number, 
/**
 * Available concurrent build permits at the time of sampling.
 */
available_build_slots: number, 
/**
 * Configured concurrent build capacity.
 */
max_concurrent_builds: number, 
/**
 * Number of persisted build history entries currently loaded.
 */
history_entries: number, 
/**
 * Whether mutating routes are disabled.
 */
read_only: boolean, 
/**
 * Whether bearer auth is mandatory for admin/mutating routes.
 */
auth_required: boolean, };
