// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a single historic compile run.
 */
export type BuildArtifactResponse = { 
/**
 * Unique run ID of the historic compilation.
 */
run: string, 
/**
 * Absolute timestamp in milliseconds when this build was completed.
 */
built_at_ms: number, 
/**
 * Size of the resulting PDF in bytes.
 */
pdf_size_bytes: number, };
