// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Envelopes the raw string content of a project's `EasyTex.toml` configuration.
 */
export type ConfigResponse = { 
/**
 * Raw TOML settings file content.
 */
raw: string, };
