// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed LaTeX linter or compiler diagnostic warning/error.
 *
 * Extracted dynamically from standard error or output streams (e.g. from Tectonic or latexmk).
 */
export type DiagnosticEvent = { 
/**
 * Severity level of the issue (typically `"warn"` or `"err"`).
 */
severity: string, 
/**
 * Absolute or relative path of the source LaTeX file where the error occurred.
 */
file: string | null, 
/**
 * Line number (1-based index) of the diagnostic target.
 */
line: number | null, 
/**
 * Column number (1-based index) of the diagnostic target.
 */
column: number | null, 
/**
 * Sanitized, human-readable description of the warning or error.
 */
message: string, 
/**
 * The exact raw log line produced by the compilation sub-process.
 */
raw: string, };
