// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lists all editable files within a project directory.
 */
export type FileListResponse = { 
/**
 * Vector of relative paths for all files with safe, editable extensions.
 */
files: Array<string>, 
/**
 * Indicates whether the search was completed successfully, or truncated due to limits.
 */
complete: boolean, };
