// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct containing the raw contents of a project file.
 */
export type FileResponse = { 
/**
 * The complete textual content of the requested document.
 */
content: string, 
/**
 * The relative, sandboxed path of the requested document from the project root.
 */
path: string, };
