// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structural report containing chktex style compiler or linter diagnostic results.
 */
export type LintResponse = { 
/**
 * True if the document has passed all check-points with zero warnings.
 */
ok: boolean, 
/**
 * Command-line exit code of the underlying linter process (`chktex`).
 */
status: number | null, 
/**
 * Standard output buffer capturing linter diagnostics.
 */
stdout: string, 
/**
 * Standard error buffer capturing process flags or configuration warnings.
 */
stderr: string, };
