// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dynamic information about the latest successful PDF compilation of a project.
 */
export type PreviewResponse = { 
/**
 * Unique identifier for the compile run (e.g. `"20260518-172100-123456_S"`).
 */
run: string, 
/**
 * Absolute timestamp in milliseconds when this PDF was generated.
 */
built_at_ms: number, 
/**
 * File size in bytes of the generated PDF.
 */
pdf_size_bytes: number, };
