// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the execution state of a specific project.
 */
export type ProjectStatusResponse = { 
/**
 * The project's active state. Typically `"building"` or `"idle"`.
 */
status: string, };
