// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List of known projects served by the current EasyTex root directory.
 */
export type ProjectsResponse = { 
/**
 * Project names sorted lexicographically.
 */
projects: Array<string>, };
