// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dynamic report of available commands and features on the host system.
 *
 * This structure is populated at startup by querying the operating system's `PATH` for specific
 * executables. It is also exported as a TypeScript definition to let the SolidJS dashboard
 * automatically show/hide features and buttons according to server capabilities.
 */
export type RuntimeCapabilities = { 
/**
 * True if `tex-fmt` is available for automatic document formatting.
 */
format: boolean, 
/**
 * True if `chktex` is available for real-time code quality linting.
 */
lint: boolean, 
/**
 * True if `synctex` is available for interactive editor-viewer navigation.
 */
synctex: boolean, 
/**
 * True if `gs` (Ghostscript) is available for compiling compressed preview PDFs.
 */
pdf_compression: boolean, 
/**
 * True if `texloganalyser` is available for extracting descriptive log analysis.
 */
log_analysis: boolean, 
/**
 * True if the server has been forced into read-only mode via configuration or environmental flags.
 */
read_only: boolean, };
