// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticEvent } from "./DiagnosticEvent";

/**
 * The set of message payloads that can be pushed over the SSE channel.
 *
 * Designed with serde-tagging (`"type": "..."`) to match idiomatic TypeScript unions on the frontend.
 */
export type ServerEvent = { "type": "status", "data": string } | { "type": "log", "data": { 
/**
 * Severity level of the log line (e.g., `"ok"`, `"warn"`, `"err"`, `"dim"`).
 */
lvl: string, 
/**
 * Raw message string.
 */
msg: string, } } | { "type": "diagnostic", "data": DiagnosticEvent } | { "type": "file_changed", "data": { 
/**
 * Relative path of the modified file.
 */
path: string, } } | { "type": "pdf", "data": string } | { "type": "stats", "data": { 
/**
 * Format string of compilation duration (e.g. `"1.2s"`).
 */
time: string, 
/**
 * Size representation of the compiled PDF on disk (e.g. `"450 KB"`).
 */
size: string, 
/**
 * Deep word count calculated across all recursive LaTeX inputs.
 */
words: number, } };
