// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Return payload for SyncTeX PDF-to-Source editing lookup request.
 */
export type SynctexEditResponse = { 
/**
 * Relative path of the corresponding LaTeX file (e.g., `"main.tex"`).
 */
file: string, 
/**
 * Line number (1-based index) matching the clicked coordinate.
 */
line: number, 
/**
 * Column number (1-based index) matching the clicked coordinate.
 */
column: number, };
