// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Return payload for SyncTeX Source-to-PDF viewing coordinates lookup request.
 */
export type SynctexViewResponse = { 
/**
 * Target page number (1-based index) inside the compiled PDF.
 */
page: number, 
/**
 * Exact horizontal page coordinate (in PDF points) matching the cursor location.
 */
x: number, 
/**
 * Exact vertical page coordinate (in PDF points) matching the cursor location.
 */
y: number, };
